### ISSUE TITLE
gem install bundler fails

### ISSUE THREAD

**Issue by PsychNStuff** [techfolios/template#10]
I receive this error after pushing a commit: Your RubyGems version (3.0.3) has a bug that prevents required_ruby_version from working for Bundler. Any scripts that use gem install bundler will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running gem update --system 3.2.3

This does not affect the current website, just changes that people may want to make.

repo url: https://github.com/PsychNStuff/psychnstuff.github.io

**Comment by philipmjohnson** [comment]
@PsychNStuff Thanks for letting me know about this. This warning occurs because the build workflow uses an out-of-date GitHub action (joshlarsen/jekyll4-deploy-gh-pages).  

Since we use custom plugins, we can't use the default GitHub Page actions for deployment. So far, I haven't found a great replacement, but I have modified the workflow to use a more recent action (helaili/jekyll-action):

https://github.com/techfolios/template/blob/main/.github/workflows/main.yml

This one generates a warning regarding an out-of-date version of Node. Sigh.

I will keep working on this. If you come up with your own approach, please let me know.

**Comment by PsychNStuff** [comment]
Thank you so much! That worked (for now) and I'll be on the lookout for other actions that might work as a replacement.

**Comment by robertgodfrey** [comment]
This Jekyll file was generated by GitHub Actions and runs without any errors or warnings: 

https://github.com/robertgodfrey/robertgodfrey.github.io/blob/main/.github/workflows/jekyll.yml

Not sure about the custom plugins, but the site seems to be working fine for me.

**Comment by philipmjohnson** [comment]
For anyone else coming across this error because they have a pre-January 2024 version of Techfolios, you need to do two things to fix your version:

1. Update your .github/workflows/main.yml file to be the same as the current template:

https://github.com/techfolios/template/blob/main/.github/workflows/main.yml

2. In your browser:
* go to your portfolio repo in GitHub, 
* click "Settings" 
* select "Pages" from the left side menu
* under "Build and Deployment", select "Github Actions"

Now you should be able to rebuild your site without problems.
