### ISSUE TITLE
Long Names Exceed Mobile Viewport Width

### ISSUE THREAD

**Issue by mdrxy** [techfolios/template#13]
On mobile displays, long names will push the navbar content off-screen, causing the width of the page to be wider than the viewport width (requiring horizontal scrolling). See:

<img width="489" alt="Screenshot 2024-03-06 at 13 55 39" src="https://github.com/techfolios/template/assets/61371264/4f590a9b-4858-46cc-a9a7-4492e432c642">
<img width="484" alt="Screenshot 2024-03-06 at 13 55 44" src="https://github.com/techfolios/template/assets/61371264/42096faf-bb6d-4c0b-ae74-6ea1f9a7b1ee">

I added an `@media` query to target mobile and a secondary shortened version of my last name to activate to address this issue, though it might be nice to have this handled by default in new sites.

[Here's my repo with the workaround](https://github.com/mdrxy/mdrxy.com)

**Comment by philipmjohnson** [comment]
Thank you!  I've added the media query to all of the default themes.

**Comment by philipmjohnson** [comment]
An additional comment from @mdrxy: 

Thank you! It should be noted that in order for this to take effect, users will need to add <a class="navbar-brand-mobile" href="{{ '/' | prepend: site.baseurl }}">Mason D.</a> to header.html after navbar-brand. I hard coded my abbreviated name, but adding site.data.bio.basics.shortname would probably be a more elegant solution so that it is set when people are configuring their bio during setup.

**Comment by philipmjohnson** [comment]
The current fix means that the name simply disappears from the navbar at mobile widths, which is not optimal.
