### ISSUE TITLE
jekyll 4.2.2 | Error:  undefined method `[]' for nil

### ISSUE THREAD

**Issue by hprutvisagar** [techfolios/template#14]
Hello, 

I am trying to update my portfolio but facing an error.

link: [hprutvisagar.github.io](https://github.com/hprutvisagar/hprutvisagar.github.io/)

error log:

jekyll 4.2.2 | Error:  undefined method `[]' for nil
C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/logger-1.6.0/lib/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
        from C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/log_adapter.rb:45:in `adjust_verbosity'
        from C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/configuration.rb:143:in `config_files'
        from C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll.rb:118:in `configuration'
        from C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:44:in `configuration_from_options'      
        from C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:83:in `block (2 levels) in init_with_program'
        from C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Users/sagar/.local/share/gem/ruby/3.3.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
        from C:/Users/sagar/AppData/Local/Microsoft/WindowsApps/jekyll:32:in `load'
        from C:/Users/sagar/AppData/Local/Microsoft/WindowsApps/jekyll:32:in `<main>'

I am not sure as to what the issue with the code is. 

Kindly helpout as i do not have CS skills to develop the ruby issues.

Kind regards
Dr. Sagar HP
sagarhp3589@gmail.com

**Comment by philipmjohnson** [comment]
There are two things you need to do:

1. In GemFile, please update Jekyll to 4.3.3:

```
gem "jekyll", "~> 4.3.3"
```

Then run `bundle install` to update Jekyll and `bundle exec jekyll serve` to rebuild your portfolio.

2. You will then find that Jekyll terminates with an error because your bio.json file is not formatted correctly.  The problem is that you are embedding HTML into the file. Specifically, on line 154, you need to change the DOI field to a simple string:

```
 "DOI":"https://doi.org/10.1088/1361-6501/ac5b2b"
```

After you make both of those corrections, your portfolio should build (at least, it did for me, locally).  You can check if it builds successfully by viewing the "Actions" page of your GitHub repository. Currently, it is failing:

https://github.com/hprutvisagar/hprutvisagar.github.io/actions
