### ISSUE TITLE
Node.js 12 actions deprecated

### ISSUE THREAD

**Issue by marcivanmanalac** [techfolios/template#8]
I added a project to my cloned repository for my techfolio and came upon a build and deploy error I haven't experienced before. I haven't updated my techfolio since fall '22 so it may be out of date, but I am unable to see what file needs to be updated for this process in the main techfolio repo. Any tips?

![image](https://user-images.githubusercontent.com/111533234/221440841-a75edcd5-f7a9-4af6-976a-0511b7285e62.png)

Here is my [repo](https://github.com/marcivanmanalac/marcivanmanalac.github.io). Anything helps :)

-Mahalo!

**Comment by marcivanmanalac** [comment]
It seems to be an issue with the .github/workflows/main.yml file. I'm not too sure what edits should I make in this?

**Comment by philipmjohnson** [comment]
So, try the following:

### 1. Delete your cache in github actions.

Click on the "Actions" tab for your repo, then on the left panel, click "Caches" and click the trash can to delete your current cache.

### 2. Update your actions. 

You should update checkout to V3, cache to V3, and json-syntax-check to V2.  See the template main.yml:

https://github.com/techfolios/template/blob/main/.github/workflows/main.yml

### 3. Commit your changes to main.yml. 

This should trigger a rebuild.

### 4. Monitor the build.

Go to the Actions tab, and watch the build.  It will take a bit longer since nothing is cached, but all the warnings should go away.


Let me know if this doesn't fix it.

**Comment by philipmjohnson** [comment]
OK, instructions to fix are attached to the issue. Good luck, let me know
if you still have problems.

**Comment by marcivanmanalac** [comment]
Professor,

My cache was already empty, but thank you! Updating the main.yaml seemed to have fixed it.
