### ISSUE TITLE
Requesting help in creating subprojects

### ISSUE THREAD

**Issue by hprutvisagar** [techfolios/template#9]
Hello,

I am trying to create my portfolio and i would like to segregate my portfolio with projects and subprojects.

I am a Ph.D., graduate in the non-CS domain and hence i am requesting your assistance. I would like to add my projects to categories.
(I have a few ML projects, Ph.D., projects, and masters projects which i would like to showcase).

My repository link is: https://github.com/hprutvisagar/hprutvisagar.github.io

Thanks in advance.

Regards
Dr. Sagar HP

**Comment by philipmjohnson** [comment]
@hprutvisagar Hi, TechFolios does have the ability to attach labels to projects in order to indicate categories such as ML, Ph.D, Masters (and any combination).

There is no mechanism at the moment to organize projects hierarchically. If it were me, I would have one single project, and then in the description, discuss its components in separate sections. 

Good luck!
